name: Sync Markdown to Strapi

on:
  push:
    paths:
      - '**/*.md'  # Trigger only when MD files change

jobs:
  sync-md:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Invoke AWS Lambda to sync files
      - name: Invoke Lambda
        uses: aws-actions/aws-lambda-invoke@v1
        with:
          function-name: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          payload: |
            {
              "files": ${{ toJson(github.event.commits.*.modified) }}
            }