name: Sync Markdown to Lambda

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  sync-markdown:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout full repository
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install AWS CLI v2
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      # 3. Prepare list of changed Markdown files
      - name: Prepare Markdown payload
        id: payload
        run: |
          files=$(git diff ${{ github.event.before }} ${{ github.sha }} --name-only | grep '\.md$' || true)
          files_json=$(printf '%s\n' "$files" | jq -R . | jq -s .)
          files_json=${files_json:-"[]"}
          echo "files=$files_json" >> $GITHUB_OUTPUT
          payload=$(jq -n --argjson files "$files_json" '{files: $files}')
          echo "payload=$payload" >> $GITHUB_OUTPUT
        shell: bash

      # 4. Invoke AWS Lambda
      - name: Invoke AWS Lambda
        run: |
          aws lambda invoke \
            --function-name "$AWS_LAMBDA_FUNCTION_NAME" \
            --region "$AWS_REGION" \
            --payload "$PAYLOAD" \
            response.json
          cat response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_LAMBDA_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          PAYLOAD: '${{ steps.payload.outputs.payload }}'