name: Sync Markdown to Lambda

on:
  push:
    branches:
      - main           # Only run on main branch
    paths:
      - '**/*.md'      # Only trigger on Markdown file changes

jobs:
  sync-markdown:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout full repository
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Important: get full Git history for git diff

      # 2. Prepare list of changed Markdown files
      - name: Prepare Markdown payload
        id: payload
        run: |
          # Get changed Markdown files between this commit and previous commit
          files=$(git diff ${{ github.event.before }} ${{ github.sha }} --name-only | grep '\.md$' || true)

          # Convert to JSON array
          files_json=$(printf '%s\n' "$files" | jq -R . | jq -s .)

          # Ensure valid JSON even if no files changed
          files_json=${files_json:-"[]"}

          # Set outputs for next step
          echo "files=$files_json" >> $GITHUB_OUTPUT
          payload=$(jq -n --argjson files "$files_json" '{files: $files}')
          echo "payload=$payload" >> $GITHUB_OUTPUT
        shell: bash

      # 3. Invoke AWS Lambda function
      - name: Invoke AWS Lambda
        uses: aws-actions/aws-cli@v2
        with:
          args: lambda invoke \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --payload '${{ steps.payload.outputs.payload }}' \
            response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # 4. Show Lambda response
      - name: Show Lambda response
        run: cat response.json