name: Sync Markdown to Lambda

on:
  push:
    paths:
      - '**/*.md'

jobs:
  sync-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Prepare payload
        id: payload
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || echo "")
          files_json=$(printf '%s\n' "$files" | jq -R . | jq -s .)
          echo "files=$files_json" >> $GITHUB_OUTPUT

          payload=$(jq -n --argjson files "$files_json" '{files: $files}')
          echo "payload=$payload" >> $GITHUB_OUTPUT

      - name: Invoke AWS Lambda
        run: |
          aws lambda invoke \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --payload "${{ steps.payload.outputs.payload }}" \
            response.json
          
          cat response.json